
# sync token: ATCTT3xFfGN0WoiqCiSe8hC-kMLS5uOZIuGT3NdXgiGTmd2YO2jF7aitLzMFgKROKDq7D042X0FJcfQt3t8jei6FM9yzhh2kSC9WbuCVKZ9_pKY3pbn4xY-a1oy-5n9bBB0KsmXC9xxYGytwvN-gODw7unfNFBwFQ8xitwHUSkp68_sllx575p8=82102422
# git config user.email 712020:06889ab2-c6f9-4f0a-9e48-d03819cf442f@bots.bitbucket.org


name: Mirror to BitBucket
run-name: Commit mirrored to BitBucket by @${{ github.actor }} at YEU



env:
  # https://bitbucket.org/  %ACCOUYNT NAME%  /  %REPO NAME%  .git
  BITBUCKET_REPO : 0verl0de/MyBitBucketRepo.git
  # Secure token
  BITBUCKET_TOKEN : ATCTT3xFfGN0hAMxaEbeGvzP14t5S5BBN3yYp7TW4t5X1Lx7F2K47CGaVNFj5A1v5lBh12DEk4BTmgpbqM4ABJbtSqlWm8mLs8AuHkU-yrozc1-jnEAuAAXq0AMj4EiZjhAMLTMvCmrTS4lAYKMCZvsk5Ept9f3NfLKELVy5OcOWW6UpCvig-JQ=3BF19963
  

# Sets permissions of the GITHUB_TOKEN
permissions:
  contents: read
  pages: write
  id-token: write
  
  
# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ "main","master" ]
  pull_request:
    branches: [ "main","master" ]

  # Create manual event trigger in Actions tab
  workflow_dispatch:

jobs:
  # clone to bitbucket
  clone:
    runs-on: ubuntu-latest
    steps:
      # Checks-out repository under $GITHUB_WORKSPACE so jobs can access it
      - uses: actions/checkout@v3
        with: 
         # ignore historical actions, only use present status
         fetch-depth: 0
         
      - name: Initiate repo in Workspace
        run: git init
        
#      - name: Specify credentials for write access to BitBucket
#        run: |
#           git config --global user.email "lode.rosseels@hotmail.com"
#           git config --global user.name "YEU"
    
           
      # Setup origin - no auth needed
      - name: Setup ORIGIN, without auth token
#        run: git remote set-url origin --add https://bitbucket.org/0verl0de/BitBucketRepo.git
        run: git remote set-url origin --add https://bitbucket.org/0verl0de/MyBitBucketRepo.git

      - name: Debug print repo connections
        run: git remote -v
        
      - name: Configure pull action
        run: |     
         git config pull.rebase false  
         git filter-branch -- --all


      - name: Pull branch to repo, use BitBucket token
#        run: git pull https://x-token-auth:ATCTT3xFfGN0PwtYGS90--6OhrWpcAY5JLAumDB-GdpKfiFqZQHymtLBFXdmJtfWnaNes8GRelVubHNVGKYjhrcGUZmoTBh2ZfdnJ_gHrJ56gpwdVbtFbmHPMaJt8LZcYvp8BSWeD6IsvnWBTttWVjwfvNBdMTjzJeunYBI7cK4S-EPrKN8Wpqw=E1633E58@bitbucket.org/0verl0de/mybitbucketrepo.git
        run: git pull https://x-token-auth:ATCTT3xFfGN0hAMxaEbeGvzP14t5S5BBN3yYp7TW4t5X1Lx7F2K47CGaVNFj5A1v5lBh12DEk4BTmgpbqM4ABJbtSqlWm8mLs8AuHkU-yrozc1-jnEAuAAXq0AMj4EiZjhAMLTMvCmrTS4lAYKMCZvsk5Ept9f3NfLKELVy5OcOWW6UpCvig-JQ=3BF19963@bitbucket.org/0verl0de/MyBitBucketRepo.git

      - name: get conflicts and merge
        run: git reset --hard origin/main
        
      - name: git push
#        run: git push -f https://x-token-auth:ATCTT3xFfGN0PwtYGS90--6OhrWpcAY5JLAumDB-GdpKfiFqZQHymtLBFXdmJtfWnaNes8GRelVubHNVGKYjhrcGUZmoTBh2ZfdnJ_gHrJ56gpwdVbtFbmHPMaJt8LZcYvp8BSWeD6IsvnWBTttWVjwfvNBdMTjzJeunYBI7cK4S-EPrKN8Wpqw=E1633E58@bitbucket.org/0verl0de/mybitbucketrepo.git
        run: git push -f https://x-token-auth:ATCTT3xFfGN0hAMxaEbeGvzP14t5S5BBN3yYp7TW4t5X1Lx7F2K47CGaVNFj5A1v5lBh12DEk4BTmgpbqM4ABJbtSqlWm8mLs8AuHkU-yrozc1-jnEAuAAXq0AMj4EiZjhAMLTMvCmrTS4lAYKMCZvsk5Ept9f3NfLKELVy5OcOWW6UpCvig-JQ=3BF19963@bitbucket.org/0verl0de/MyBitBucketRepo.git
